### ISSUE TITLE
Unhelpful apischema error when submodules not initialised

### ISSUE THREAD

**Issue by GDYendell** [epics-containers/pvi#17]
```
❯ make
make -C ./configure install 
make[1]: Entering directory `/tmp/pvi-test/ADCore/configure'
make -C O.linux-x86_64 -f ../Makefile TOP=../.. \
    T_A=linux-x86_64 install
pvi found: /tmp/pvi-test/venv/bin/pvi
make[2]: Entering directory `/tmp/pvi-test/ADCore/configure/O.linux-x86_64'
perl /dls_sw/epics/R3.14.12.7/base/bin/linux-x86_64/convertRelease.pl checkRelease
make[2]: Leaving directory `/tmp/pvi-test/ADCore/configure/O.linux-x86_64'
make[1]: Leaving directory `/tmp/pvi-test/ADCore/configure'
make -C ./ADApp install 
make[1]: Entering directory `/tmp/pvi-test/ADCore/ADApp'
make -C ./Db install 
pvi found: /tmp/pvi-test/venv/bin/pvi
make[2]: Entering directory `/tmp/pvi-test/ADCore/ADApp/Db'
make -C O.linux-x86_64 -f ../Makefile TOP=../../.. \
    T_A=linux-x86_64 install
pvi found: /tmp/pvi-test/venv/bin/pvi
make[3]: Entering directory `/tmp/pvi-test/ADCore/ADApp/Db/O.linux-x86_64'
/tmp/pvi-test/venv/bin/pvi produce ADDriverParameters.template ../../../pvi/ADDriver.pvi.producer.yaml
Traceback (most recent call last):

  File "/tmp/pvi-test/venv/bin/pvi", line 11, in <module>
    sys.exit(app())

  File "/tmp/pvi-test/venv/lib/python3.7/site-packages/pvi/__main__.py", line 69, in produce
    producer_inst = deserialize_yaml(Producer, producer)

  File "/tmp/pvi-test/venv/lib/python3.7/site-packages/pvi/_yaml_utils.py", line 32, in deserialize_yaml
    return deserialize(cls, d)

  File "/tmp/pvi-test/venv/lib/python3.7/site-packages/apischema/utils.py", line 400, in wrapper
    return wrapped(*args, **kwargs)

  File "/tmp/pvi-test/venv/lib/python3.7/site-packages/apischema/deserialization/__init__.py", line 903, in deserialize
    )(data)

  File "apischema/deserialization/methods.pyx", line 655, in apischema.deserialization.methods.ConversionMethod.deserialize

  File "apischema/deserialization/methods.pyx", line 656, in apischema.deserialization.methods.ConversionMethod.deserialize

  File "apischema/deserialization/methods.pyx", line 1176, in apischema.deserialization.methods.ConversionMethod_deserialize

  File "apischema/deserialization/methods.pyx", line 1305, in apischema.deserialization.methods.DeserializationMethod_deserialize

  File "apischema/deserialization/methods.pyx", line 1078, in apischema.deserialization.methods.ObjectMethod_deserialize

apischema.validation.errors.ValidationError: ValidationError: [{'loc': ['parameters', 0, 'children'], 'err': 'unexpected property'}, {'loc': ['parameters', 0, 'children'], 'err': 'unexpected property'}, {'loc': ['parameters', 0, 'children'], 'err': 'unexpected property'}, {'loc': ['parameters', 0, 'children'], 'err': 'unexpected property'}, {'loc': ['parameters', 0, 'children'], 'err': 'unexpected property'}, {'loc': ['parameters', 0, 'children'], 'err': 'unexpected property'}, {'loc': ['parameters', 0, 'children'], 'err': 'unexpected property'}, {'loc': ['parameters', 0, 'children'], 'err': 'unexpected property'}, {'loc': ['parameters', 0, 'children', 2, 'children'], 'err': 'missing property'}, {'loc': ['parameters', 0, 'children', 2, 'description'], 'err': 'unexpected property'}, {'loc': ['parameters', 0, 'children', 2, 'drv_info'], 'err': 'unexpected property'}, {'loc': ['parameters', 0, 'children', 2, 'index_name'], 'err': 'unexpected property'}, {'loc': ['parameters', 0, 'children', 2, 'initial'], 'err': 'not matching pattern (\\$\\(\\w+=([0-1])\\)) (pattern)'}, {'loc': ['parameters', 0, 'children', 2, 'initial'], 'err': 'expected type null, found string'}, {'loc': ['parameters', 0, 'children', 2, 'initial'], 'err': 'expected type integer, found string'}, {'loc': ['parameters', 0, 'children', 2, 'initial'], 'err': 'not matching pattern (\\$\\(\\w+=([0-1])\\)) (pattern)'},

...
```

**Comment by GDYendell** [comment]
Makefile integration not needed anymore.
